package ServiceNow.PlatformBusinessApps.NERD.selenium.Constants;

import com.nci.automation.web.CommonUtils;

public class NCI_Staff_Members_Constants {

    /* CRS KNOWLEDGE MANAGEMENT SYSTEM TEXT MAIN PAGE */
    public static final String CRS_KNOWLEDGE_MANAGEMENT_SYSTEM_TEXT_MAIN_PAGE  = "CRS Knowledge Management System";

    /* CRS COLLABORATION NEW SUBMISSION TITLE TEXT BOX */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_TITLE_TEXT_BOX  = "Testing Category" + CommonUtils.lastNameRandomizer();

    /* CRS COLLABORATION NEW SUBMISSION PLEASE SPECIFY DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_PLEASE_SPECIFY_DROP_DOWN  = "New";

    /* CRS COLLABORATION NEW SUBMISSION FISCAL YEAR DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_FISCAL_YEAR_DROP_DOWN   = "2024";

    /* CRS COLLABORATION NEW SUBMISSION DESCRIPTION TEXT BOX */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_DESCRIPTION_TEXT_BOX  = "Description for Testing Category";

    /* CRS COLLABORATION NEW SUBMISSION FY THE COLLABORATIVE ACTIVITY ORIGINATED DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_FY_THE_COLLABORATIVE_ACTIVITY_ORIGINATED_DROP_DOWN  = "2022";

    /* CRS COLLABORATION NEW SUBMISSION LEAD DOC DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_LEAD_DOC_DROP_DOWN  = "CBIIT";

    /* CRS COLLABORATION NEW SUBMISSION POC TEXT BOX */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_POC_TEXT_BOX  = "TesT";

    /* CRS COLLABORATION NEW SUBMISSION NIH ICS/OD COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_NIH_ICS_OD_COLLABORATORS_DROP_DOWN  = "No NIH IC/OD Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION HHS AGENCY COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_HHS_AGENCY_COLLABORATORS_DROP_DOWN  = "No HHS Agency Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION OTHER FEDERAL AGENCY COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_OTHER_FEDERAL_AGENCY_COLLABORATORS_DROP_DOWN  = "No Federal Agency Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION TRIBAL/STATE/LOCAL GOVERNMENT COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_TRIBAL_STATE_LOCAL_GOVERNMENT_COLLABORATORS_DROP_DOWN  = "No Tribal/State/Local/Government Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION FOREIGN GOVERNMENT COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_FOREIGN_GOVERNMENT_COLLABORATORS_DROP_DOWN  = "No Foreign Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION NON-GOVERNMENTAL COLLABORATORS DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_NON_GOVERNMENTAL_COLLABORATORS_DROP_DOWN  = "No Non-Governmental Collaborators";

    /* CRS COLLABORATION NEW SUBMISSION IS THIS COLLABORATION RELATED TO A REGULATORY ACTIVITY DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_IS_THIS_COLLABORATION_RELATED_TO_A_REGULATORY_ACTIVITY_DROP_DOWN  = "Yes";

    /* CRS COLLABORATION NEW SUBMISSION WAS NIH FUNDING PROVIDED FOR THIS ACTIVITY DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_WAS_NIH_FUNDING_PROVIDED_FOR_THIS_ACTIVITY_DROP_DOWN  = "Yes";

    /* CRS COLLABORATION NEW SUBMISSION NIH STRATEGIC ALIGNMENT DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_NIH_STRATEGIC_ALIGNMENT_DROP_DOWN  = "Objective 1: Advancing Biomedical and Behavioral Sciences";

    /* CRS COLLABORATION NEW SUBMISSION HHS STRATEGIC PLAN ALIGNMENT DROP DOWN */
    public static final String CRS_COLLABORATION_NEW_SUBMISSION_HHS_STRATEGIC_PLAN_ALIGNMENT_DROP_DOWN  = "Strategic Goal 1: Reform, Strengthen, and Modernize the Nation's Healthcare System";
}
