package ServiceNow.PlatformBusinessApps.NERD.Constants;

import com.nci.automation.web.CommonUtils;

public class Covid19ActivitiesSubmissions_Constants {

    /* COVID-19 NEW SUBMISSION TITLE TEXT BOX */
    public static final String COVID_19_NEW_SUBMISSION_TITLE_TEXT_BOX  = "Covid-19 Testing Category" + CommonUtils.lastNameRandomizer();

    /* COVID-19 NEW SUBMISSION DOC DROP DOWN */
    public static final String COVID_19_NEW_SUBMISSION_DOC_DROP_DOWN  = "CBIIT";

    /* COVID-19 NEW SUBMISSION NCI ACTIVITIES DROP DOWN */
    public static final String COVID_19_NEW_SUBMISSION_NCI_ACTIVITIES_DROP_DOWN  = "Serology";

    /* COVID-19 SUBMISSION VIEW RECORD CATEGORY HEADER */
    public static final String COVID_19_SUBMISSION_VIEW_RECORD_CATEGORY_HEADER = "Category";

    /* COVID-19 SUBMISSION VIEW RECORD CATEGORY VALUE  */
    public static final String COVID_19_SUBMISSION_VIEW_RECORD_CATEGORY_VALUE = "COVID-19 Activities";

    /* COVID-19 SUBMISSION VIEW RECORD SPECIAL TOPIC HEADER  */
    public static final String COVID_19_SUBMISSION_VIEW_RECORD_SPECIAL_TOPIC_HEADER = "Special Topic";

    /* COVID-19 SUBMISSION VIEW RECORD SPECIAL TOPIC FILTER VALUE  */
    public static final String COVID_19_SUBMISSION_VIEW_RECORD_SPECIAL_TOPIC_FILTER_VALUE = "Big data/Data sharing";

    /* COVID-19 SUBMISSION VIEW RECORD SPECIAL TOPIC COVID19 FILTER VALUE  */
    public static final String COVID_19_SUBMISSION_VIEW_RECORD_SPECIAL_TOPIC_COVID19_FILTER_VALUE = "COVID-19";

    /* OTHER ACCOMPLISHMENTS NEW SUBMISSION TITLE TEXT BOX */
    public static final String OTHER_ACCOMPLISHMENTS_NEW_SUBMISSION_TITLE_TEXT_BOX  = "Other Accomplishments Testing Category" + CommonUtils.lastNameRandomizer();

    /* OTHER ACCOMPLISHMENTS SUBMISSION VIEW RECORD CATEGORY VALUE  */
    public static final String OTHER_ACCOMPLISHMENTS_SUBMISSION_VIEW_RECORD_CATEGORY_VALUE = "Other Accomplishments";

    /* OTHER ACCOMPLISHMENTS SUBMISSION VIEW RECORD SPECIAL TOPIC FILTER VALUE  */
    public static final String OTHER_ACCOMPLISHMENTS_SUBMISSION_VIEW_RECORD_SPECIAL_TOPIC_FILTER_VALUE = "COVID-19";
}
