package ServiceNow.PlatformBusinessApps.SSJ.playwright.Utils;

import com.beust.ah.A;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

public class SSJ_Constants {

    public static final ArrayList<String> POSITION_NAMES = new ArrayList<>() {
        {
            add("Assistant Clinical Investigator (HS)");
            add("Assistant Clinical Investigator 1");
            add("Assistant Clinical Investigator 2");
            add("Clinical Fellow");
            add("Investigator (HS)");
            add("Investigator 1");
            add("Investigator 2");
            add("N/A");
            add("Research Fellow");
            add("SBRBPAS");
            add("Science Policy Leader Tier 2");
            add("Science Program Leader Tier 2");
            add("Scientific Executive");
            add("Senior Clinical Fellow");
            add("Senior Clinician");
            add("Senior Clinician (HS)");
            add("Senior Investigator");
            add("Senior Investigator (HS)");
            add("Senior Research Fellow");
            add("Senior Scientific Officer");
            add("Senior Scientist");
            add("Staff Clinician (HS)");
            add("Staff Clinician 1");
            add("Staff Clinician 2");
            add("Staff Scientist 1");
            add("Staff Scientist 2");
            add("Staff Scientist 2 (Clinical)");
            add("Staff Scientist 2 (Facility Head)");
        }
    };

    public static final ArrayList<String> ORG_CODES = new ArrayList<String>() {
        {
            add("HNC");
            add("HNC1");
            add("HNC14");
            add("HNC141");
            add("HNC1412");
            add("HNC14P");
            add("HNC14P2");
            add("HNC14P3");
            add("HNC14P4");
            add("HNC14Q");
            add("HNC14Q2");
            add("HNC14Q3");
            add("HNC14Q4");
            add("HNC14Q5");
            add("HNC14Q6");
            add("HNC14T");
            add("HNC14T2");
            add("HNC14T3");
            add("HNC14T4");
            add("HNC14W");
            add("HNC14X");
            add("HNC14X2");
            add("HNC14X3");
            add("HNC14X4");
            add("HNC17");
            add("HNC177");
            add("HNC1772");
            add("HNC1773");
            add("HNC178");
            add("HNC1782");
            add("HNC1784");
            add("HNC1785");
            add("HNC1786");
            add("HNC17B");
            add("HNC17B1");
            add("HNC17B2");
            add("HNC17B3");
            add("HNC17B4");
            add("HNC17B5");
            add("HNC17B6");
            add("HNC17B7");
            add("HNC17C");
            add("HNC17C2");
            add("HNC17C3");
            add("HNC17C4");
            add("HNC17C5");
            add("HNC17F");
            add("HNC17G");
            add("HNC17H");
            add("HNC17H2");
            add("HNC17H3");
            add("HNC17J");
            add("HNC17K");
            add("HNC17K2");
            add("HNC17L");
            add("HNC17M");
            add("HNC17N");
            add("HNC17N3");
            add("HNC17N4");
            add("HNC17N5");
            add("HNC17N6");
            add("HNC17N7");
            add("HNC17P");
            add("HNC17Q");
            add("HNC17S");
            add("HNC17T");
            add("HNC17U");
            add("HNC17V");
            add("HNC17W");
            add("HNC17X");
            add("HNC17Y");
            add("HNC1D");
            add("HNC1D1");
            add("HNC1D2");
            add("HNC1D22");
            add("HNC1D23");
            add("HNC1D24");
            add("HNC1D3");
            add("HNC1D4");
            add("HNC1D42");
            add("HNC1D43");
            add("HNC1D44");
            add("HNC1D6");
            add("HNC1D62");
            add("HNC1D63");
            add("HNC1E");
            add("HNC1E2");
            add("HNC1E4");
            add("HNC1H");
            add("HNC1H2");
            add("HNC1H3");
            add("HNC1H4");
            add("HNC1H5");
            add("HNC1H6");
            add("HNC1J");
            add("HNC1K");
            add("HNC1L");
            add("HNC1L4");
            add("HNC1M");
            add("HNC1N");
            add("HNC1N2");
            add("HNC1N3");
            add("HNC1P");
            add("HNC1P2");
            add("HNC1P3");
            add("HNC1Q");
            add("HNC1Q2");
            add("HNC1Q3");
            add("HNC1Q4");
            add("HNC1R");
            add("HNC1S");
            add("HNC1S2");
            add("HNC1S3");
            add("HNC1S4");
            add("HNC1S41");
            add("HNC1S42");
            add("HNC1S421");
            add("HNC1S422");
            add("HNC1S423");
            add("HNC1S43");
            add("HNC1S431");
            add("HNC1S432");
            add("HNC1S433");
            add("HNC1S434");
            add("HNC1S44");
            add("HNC1S441");
            add("HNC1S442");
            add("HNC1S443");
            add("HNC1S45");
            add("HNC1S46");
            add("HNC1S461");
            add("HNC1S462");
            add("HNC1S463");
            add("HNC4");
            add("HNC41");
            add("HNC413");
            add("HNC414");
            add("HNC42");
            add("HNC43");
            add("HNC44");
            add("HNC49");
            add("HNC4B");
            add("HNC4C");
            add("HNC4D");
            add("HNC4G");
            add("HNC4H");
            add("HNC4J");
            add("HNC5");
            add("HNC51");
            add("HNC519");
            add("HNC51A");
            add("HNC52");
            add("HNC522");
            add("HNC523");
            add("HNC53");
            add("HNC535");
            add("HNC536");
            add("HNC537");
            add("HNC538");
            add("HNC539");
            add("HNC53A");
            add("HNC7");
            add("HNC71");
            add("HNC71-2");
            add("HNC713");
            add("HNC716");
            add("HNC717");
            add("HNC718");
            add("HNC719");
            add("HNC71A");
            add("HNC71B");
            add("HNC72");
            add("HNC723");
            add("HNC724");
            add("HNC725");
            add("HNC726");
            add("HNC727");
            add("HNC728");
            add("HNC729");
            add("HNC74");
            add("HNC76");
            add("HNC763");
            add("HNC78");
            add("HNC79");
            add("HNC794");
            add("HNC795");
            add("HNC796");
            add("HNC797");
            add("HNC799");
            add("HNC79B");
            add("HNC7B");
            add("HNC7B2");
            add("HNC7B4");
            add("HNC7B5");
            add("HNC7B6");
            add("HNC7B7");
            add("HNC7B9");
            add("HNC7BA");
            add("HNC7J");
            add("HNC7K");
            add("HNC7K4");
            add("HNC7L");
            add("HNC7L4");
            add("HNC7R");
            add("HNC7Y");
            add("HNC7Z02");
            add("HNC7Z04");
            add("HNC7Z05");
            add("HNC7Z06");
            add("HNC7Z063");
            add("HNC7Z07");
            add("HNC7Z11");
            add("HNC7Z114");
            add("HNC7Z115");
            add("HNC7Z12");
            add("HNC7Z123");
            add("HNC7Z124");
            add("HNC7Z16");
            add("HNC7Z17");
            add("HNC7Z18");
            add("HNC7Z19");
            add("HNC7Z20");
            add("HNC7Z23");
            add("HNC7Z24");
            add("HNC7Z25");
            add("HNC7Z26");
            add("HNC7Z27");
            add("HNC7Z28");
            add("HNC7Z30");
            add("HNC7Z32");
            add("HNC7Z322");
            add("HNC7Z323");
            add("HNC7Z324");
            add("HNC7Z325");
            add("HNC7Z37");
            add("HNC7Z38");
            add("HNC7Z41");
            add("HNC7Z42");
            add("HNC7Z43");
            add("HNC7Z45");
            add("HNC7Z46");
            add("HNC7Z47");
            add("HNC7Z48");
            add("HNC7Z49");
            add("HNC7Z50");
            add("HNC7Z52");
            add("HNC7Z53");
            add("HNC7Z54");
            add("HNC7Z55");
            add("HNC7Z56");
            add("HNC7Z57");
            add("HNC7Z58");
            add("HNC7Z59");
            add("HNC9");
            add("HNC91");
            add("HNC913");
            add("HNC914");
            add("HNC9B");
            add("HNC9B2");
            add("HNC9B4");
            add("HNC9B5");
            add("HNC9C");
            add("HNC9C2");
            add("HNC9C3");
            add("HNC9C5");
            add("HNC9C6");
            add("HNC9C7");
            add("HNC9C8");
            add("HNC9C9");
            add("HNC9CA");
            add("HNCB");
            add("HNCB1");
            add("HNCB13");
            add("HNCB14");
            add("HNCB2");
            add("HNCB22");
            add("HNCB24");
            add("HNCB25");
            add("HNCB3");
            add("HNCB32");
            add("HNCB33");
            add("HNCB35");
            add("HNCB36");
            add("HNCB37");
            add("HNCB38");
            add("HNCB39");
            add("HNCB4");
            add("HNCB42");
            add("HNCB44");
            add("HNCB45");
            add("HNCB46");
            add("HNCB47");
            add("HNCB48");
            add("HNCB49");
            add("HNCB4C");
            add("HNCB4D");
            add("HNCB4E");
            add("HNCB4F");
            add("HNCB6");
            add("HNCB62");
            add("HNCB63");
            add("HNCB64");
            add("HNCB65");
            add("HNCB8");
            add("HNCB82");
            add("HNCB83");
            add("HNCB84");
            add("HNCB85");
            add("HNCB86");
            add("HNCB9");
            add("HNCBA");
            add("HNCBA2");
            add("HNCBA3");
            add("HNCC");
            add("HNCC1");
            add("HNCC6");
            add("HNCCA");
            add("HNCCB");
            add("HNCCC");
            add("HNCCD");
            add("HNCCE");
            add("HNCD");
            add("HNCD1");
            add("HNCD2");
            add("HNCD22");
            add("HNCD23");
            add("HNCD24");
            add("HNCD25");
            add("HNCD26");
            add("HNCD3");
            add("HNCD36");
            add("HNCD38");
            add("HNCD39");
            add("HNCD3A");
            add("HNCD3B");
            add("HNCD4");
            add("HNCD43");
            add("HNCD45");
            add("HNCD46");
            add("HNCD48");
            add("HNCD49");
            add("HNCD5");
            add("HNCD52");
            add("HNCD53");
            add("HNCD54");
            add("HNCD55");
        }
    };
}

