package ServiceNow.PlatformBusinessApps.ETracking.Constants;

import com.nci.automation.web.CommonUtils;

public class EtrackAssetsRecords_NativeView_Constants {

    /* ETRACKING USER NAME */
    public static final String ETRACKING_USER_NAME = "Jeffrey Alderdice";

    /* ETRACKING NATIVE VIEW FILTER NAVIGATION SEARCH BOX */
   public static final String ETRACKING_NATIVE_VIEW_FILTER_NAVIGATION_SEARCH_BOX = "eTracking";

    /* ETRACKING NATIVE VIEW ASSETS ALL RECORD SEARCH DROP DOWN */
    public static final String ETRACKING_NATIVE_VIEW_ASSETS_ALL_RECORD_SEARCH_DROP_DOWN = "barcode";

    /* ETRACKING ASSETS NEW RECORD DECAL NUMBER TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_DECAL_NUMBER_TEXT_BOX  = "New Decal Number 123 Test " + CommonUtils.lastNameRandomizer();

    /* ETRACKING ASSETS NEW RECORD MODEL TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_MODEL_TEXT_BOX  = "Tarp";

    /* ETRACKING ASSETS NEW RECORD QUANTITY TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_QUANTITY_TEXT_BOX  = "10";

    /* ETRACKING ASSETS NEW RECORD COST TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_COST_TEXT_BOX  = "100";

    /* ETRACKING ASSETS NEW RECORD STOCKROOM TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_STOCKROOM_TEXT_BOX  = "Ayele #1E240";

    /* ETRACKING ASSETS NEW RECORD ASSET TYPE TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_ASSET_TYPE_TEXT_BOX  = "Asset Type";

    /* ETRACKING ASSETS NEW RECORD EXPIRATION DATE TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_EXPIRATION_DATE_TEXT_BOX  = "01/01/2030";

    /* ETRACKING ASSETS NEW RECORD ASSET INFORMATION TEXT BOX */
    public static final String ETRACKING_ASSETS_NEW_RECORD_ASSET_INFORMATION_TEXT_BOX  = "Test Asset Information";

 /* ETRACKING ASSETS NEW RECORD ASSET INFORMATION TEXT BOX EXPECTED LENGTH */
 public static final String ETRACKING_ASSETS_NEW_RECORD_ASSET_INFORMATION_TEXT_BOX_EXPECTED_LENGTH  = "1100";

    /* ETRACKING ASSETS NEW RECORD STATUS DROP DOWN */
    public static final String ETRACKING_ASSETS_NEW_RECORD_STATUS_DROP_DOWN  = "Checked out";

    /* ETRACKING ASSETS OPEN RECORD DELETE BUTTON */
    public static final String ETRACKING_ASSETS_OPEN_RECORD_DELETE_BUTTON  = "Delete";

    /* ETRACKING ASSETS MODEL RECORD DESCRIPTION TEXT BOX */
    public static final String ETRACKING_ASSETS_MODEL_RECORD_DESCRIPTION_TEXT_BOX  = "ASSETS MODEL RECORD DESCRIPTION TEXT BOX ";

}
