package CHARMS.scenariosData;

import APPS_COMMON.PageInitializers.PageInitializer;
import CHARMS.constants.CHARMS_Data_File_Path_Constants;
import CHARMS.constants.MetforminScreenerConstants;
import com.nci.automation.utils.ExcelReader;
import java.util.Map;

public class MetforminScreener_TestDataManager extends PageInitializer {
    /* Metformin Screener Data */
    public Map<String, String> testDataForMetforminScreener;

    public String areYouCompletingThisQuestionnaireForSomeoneElse;
    public String whatIsYourName;
    public String firstName;
    public String middleInitial;
    public String lastName;
    public String theNextSetOfQuestionsWillCollectBasicInformationAboutYouTheParticipant;
    public String whatIsYourTheParticipantsDateOfBirth;
    public String whatIsYouTheParticipantsSex;
    public String areYouTheParticipantAdopted;
    public String inWhichCountryDoYouTheParticipantCurrentlyLive;
    public String pleaseProvideTheMailingAddressWhereStudyMaterialsCanBeSentAsNeeded;
    public String street;
    public String street2Optional;
    public String city;
    public String stateAbbreviation;
    public String zipCode;
    public String whatIsYourTheParticipantsEmailAddress;
    public String pleaseConfirmYourTheParticipantsEmailAddress;
    public String pleaseListYourTheParticipantsPhoneNumbersBelowAndIncludeCountryCode;
    public String pleaseAlsoSelectYourPreferredContactNumber;
    public String homePhoneNumber;
    public String workPhoneNumber;
    public String preferred;
    public String cellPhoneNumber;
    public String whatIsYourTheParticipantsRacePleaseSelectAllThatApply;
    public String whatIsYourTheParticipantsEthnicity;
    public String haveYouTheParticipantEverParticipatedInALiFraumeniSyndromeStudy;
    public String egAtAnotherMedicalInstitutionUniversityGovernmentAgencyOrOtherSite;
    public String pleaseSpecifyTheStudiesOrRegistryGroupsRegardingParticipationInOtherStudies;
    public String doYouCurrentlyReceiveRegularLiFraumeniSyndromeScreeningOrManagement;
    public String provideInformationAboutTheInstitutionWhereYouTheParticipantReceiveRegularLiFraumeniSyndromeManagement;
    public String physicianName;
    public String institutionName;
    public String cityStateProvince;
    public String phoneNumber;
    public String deliveryInformation;
    public String haveYouTheParticipantBeenDiagnosedWithLiFraumeniSyndrome;
    public String haveYouTheParticipantHadGeneticTestingForTheTP53Gene;
    public String areYouTheParticipantCurrentlyPregnant;
    public String wereYouTheParticipantDiagnosedWithCongenitalLacticAcidosis;
    public String haveYouTheParticipantEverBeenDiagnosedWithCancer;
    public String haveYouTheParticipantHadSurgeryToRemoveCancerLast3Months;
    public String haveYouTheParticipantReceivedChemotherapyOrRadiationLast6Months;
    public String whatWasTheDateOfParticipantLastTreatment;
    public String areYouTheParticipantCurrentlyUndergoingTreatmentForCancer;
    public String doYouTheParticipantHaveAKnownAllergyToMetformin;
    public String haveYouTheParticipantEverTakenMetformin;
    public String haveYouTheParticipantTakenMetforminForMoreThan3MonthsInTotal;
    public String areYouTheParticipantCurrentlyTakingMetformin;
    public String howDidYouTheParticipantHearAboutThisStudy;
    public String hereAreAFewRemainingQuestionsRegardingThisStudy;
    public String name;
    public String address;
    public String medicalPhoneNumber;
    public String doWeHaveYourTheParticipantsPermissionToCallThisIndividualToSeekMoreInformation;
    public String whatAreTheMainReasonsForParticipatingInThisStudySelectAllThatApply;
    public String receiveGeneticTesting;
    public String whatWasTheResultOfYourTheParticipantsTP53GeneticTesting;
    public String howWouldYouLikeToProvideYourGeneticTestResults;
    public String deliveryHelpText;
    public String tumorType;
    public String Age;
    public String pleaseProvideTheDateOfSurgery;
    public String listAllMedicationsAndSeparateWithASemicolon;
    public String pleaseSelectAgeOrDateForReporting;
    public String ageAtDiagnosis;
    public String areYouTheParticipantCurrentlyReceivingTreatment;
    public String pleaseProvideTheNameOfTheInstitutionWhereTheCancerWasDiagnosed;
    public String pleaseProvideTheNameOfTheInstitutionWhereTheCancerWasTreated;
    public String pleaseProvideTheNameOfTheTreatingPhysician;
    public String additionalDetails;
    public String monthOfDiagnosis;
    public String yearOfDiagnosis;
    public String submit_Screen_text1;
    public String submit_Screen_text2;
    public String submit_Screen_text3;
    public String OK;
    public String proxyFirstName;
    public String proxyMiddleInitial;
    public String proxyLastName;

    /* FETCHING DATA FROM EXCEL BEFORE SUBMITTING METFORMIN SCREENER FORM */
    public void dataInitializerMetforminScreener(String sheetName) {
        /* ****** METFORMIN SCREENER FORM ***** */
        if (sheetName.equals("MetforminScreenerScenario1")) {
            testDataForMetforminScreener = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.METFORMIN_SCREENER_DATA, sheetName);
            System.out.println("HELLO");
            areYouCompletingThisQuestionnaireForSomeoneElse = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_COMPLETING_THIS_QUESTIONNAIRE_FOR_SOMEONE_ELSE);
            whatIsYourName = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_NAME);
            firstName = testDataForMetforminScreener.get(MetforminScreenerConstants.FIRST_NAME);
            middleInitial = testDataForMetforminScreener.get(MetforminScreenerConstants.MIDDLE_INITIAL);
            lastName = testDataForMetforminScreener.get(MetforminScreenerConstants.LAST_NAME);
            theNextSetOfQuestionsWillCollectBasicInformationAboutYouTheParticipant = testDataForMetforminScreener.get(MetforminScreenerConstants.THE_NEXT_SET_OF_QUESTIONS_WILL_COLLECT_BASIC_INFORMATION_ABOUT_YOU_THE_PARTICIPANT);
            whatIsYourTheParticipantsDateOfBirth = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_THE_PARTICIPANTS_DATE_OF_BIRTH);
            whatIsYouTheParticipantsSex = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_THE_PARTICIPANTS_SEX);
            areYouTheParticipantAdopted = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_THE_PARTICIPANT_ADOPTED);
            inWhichCountryDoYouTheParticipantCurrentlyLive = testDataForMetforminScreener.get(MetforminScreenerConstants.IN_WHICH_COUNTRY_DO_YOU_THE_PARTICIPANT_CURRENTLY_LIVE);
            pleaseProvideTheMailingAddressWhereStudyMaterialsCanBeSentAsNeeded = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_PROVIDE_THE_MAILING_ADDRESS_WHERE_STUDY_MATERIALS_CAN_BE_SENT_AS_NEEDED);
            street = testDataForMetforminScreener.get(MetforminScreenerConstants.STREET);
            street2Optional = testDataForMetforminScreener.get(MetforminScreenerConstants.STREET_2_OPTIONAL);
            city = testDataForMetforminScreener.get(MetforminScreenerConstants.CITY);
            stateAbbreviation = testDataForMetforminScreener.get(MetforminScreenerConstants.STATE_ABBREVIATION);
            zipCode = testDataForMetforminScreener.get(MetforminScreenerConstants.ZIP_CODE);
            whatIsYourTheParticipantsEmailAddress = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_THE_PARTICIPANTS_EMAIL_ADDRESS);
            pleaseConfirmYourTheParticipantsEmailAddress = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_CONFIRM_YOUR_THE_PARTICIPANTS_EMAIL_ADDRESS);
            pleaseListYourTheParticipantsPhoneNumbersBelowAndIncludeCountryCode = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_LIST_YOUR_THE_PARTICIPANTS_PHONE_NUMBERS_BELOW_AND_INCLUDE_COUNTRY_CODE);
            pleaseAlsoSelectYourPreferredContactNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_ALSO_SELECT_YOUR_PREFERRED_CONTACT_NUMBER);
            homePhoneNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.HOME_PHONE_NUMBER);
            workPhoneNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.WORK_PHONE_NUMBER);
            preferred = testDataForMetforminScreener.get(MetforminScreenerConstants.PREFERRED);
            cellPhoneNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.CELL_PHONE_NUMBER);
            whatIsYourTheParticipantsRacePleaseSelectAllThatApply = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_THE_PARTICIPANTS_RACE_PLEASE_SELECT_ALL_THAT_APPLY);
            whatIsYourTheParticipantsEthnicity = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_IS_YOUR_THE_PARTICIPANTS_ETHNICITY);
            haveYouTheParticipantEverParticipatedInALiFraumeniSyndromeStudy = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_EVER_PARTICIPATED_IN_A_LIFRAUMENI_SYNDROME_STUDY);
            egAtAnotherMedicalInstitutionUniversityGovernmentAgencyOrOtherSite = testDataForMetforminScreener.get(MetforminScreenerConstants.EG_AT_ANOTHER_MEDICAL_INSTITUTION_UNIVERSITY_GOVERNMENT_AGENCY_OR_OTHER_SITE);
            pleaseSpecifyTheStudiesOrRegistryGroupsRegardingParticipationInOtherStudies = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_SPECIFY_THE_STUDYIES_OR_REGISTRY_GROUPS_REGARDING_PARTICIPATION_IN_OTHER_STUDIES);
            doYouCurrentlyReceiveRegularLiFraumeniSyndromeScreeningOrManagement = testDataForMetforminScreener.get(MetforminScreenerConstants.DO_YOU_CURRENTLY_RECEIVE_REGULAR_LI_FRAUMENI_SYNDROME_SCREENING_OR_MANAGEMENT);
            provideInformationAboutTheInstitutionWhereYouTheParticipantReceiveRegularLiFraumeniSyndromeManagement = testDataForMetforminScreener.get(MetforminScreenerConstants.PROVIDE_INFORMATION_ABOUT_THE_INSTITUTION_WHERE_YOU_THE_PARTICIPANT_RECEIVE_REGULAR_LIFRAUMENI_SYNDROME_MANAGEMENT);
            physicianName = testDataForMetforminScreener.get(MetforminScreenerConstants.PHYSICIAN_NAME);
            institutionName = testDataForMetforminScreener.get(MetforminScreenerConstants.INSTITUTION_NAME);
            cityStateProvince = testDataForMetforminScreener.get(MetforminScreenerConstants.CITY_STATE_PROVINCE);
            phoneNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.PHONE_NUMBER);
            deliveryInformation = testDataForMetforminScreener.get(MetforminScreenerConstants.DELIVERY_INFORMATION);
            haveYouTheParticipantBeenDiagnosedWithLiFraumeniSyndrome = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_BEEN_DIAGNOSED_WITH_LI_FRAUMENI_SYNDROME);
            haveYouTheParticipantHadGeneticTestingForTheTP53Gene = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_HAD_GENETIC_TESTING_FOR_THE_TP53_GENE);
            whatWasTheResultOfYourTheParticipantsTP53GeneticTesting = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_WAS_THE_RESULT_OF_YOUR_THE_PARTICIPANTS_TP53_GENETIC_TESTING);
            howWouldYouLikeToProvideYourGeneticTestResults = testDataForMetforminScreener.get(MetforminScreenerConstants.HOW_WOULD_YOU_LIKE_TO_PROVIDE_YOUR_GENETIC_TEST_RESULTS);
            deliveryHelpText = testDataForMetforminScreener.get(MetforminScreenerConstants.DELIVERY_HELP_TEXT);
            areYouTheParticipantCurrentlyPregnant = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_THE_PARTICIPANT_CURRENTLY_PREGNANT);
            wereYouTheParticipantDiagnosedWithCongenitalLacticAcidosis = testDataForMetforminScreener.get(MetforminScreenerConstants.WERE_YOU_THE_PARTICIPANT_DIAGNOSED_WITH_CONGENITAL_LACTIC_ACIDOSIS);
            haveYouTheParticipantEverBeenDiagnosedWithCancer = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_EVER_BEEN_DIAGNOSED_WITH_CANCER);
            tumorType = testDataForMetforminScreener.get(MetforminScreenerConstants.TUMOR_TYPE);
            Age = testDataForMetforminScreener.get(MetforminScreenerConstants.AGE);
            pleaseSelectAgeOrDateForReporting = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_SELECT_AGE_OR_DATE_FOR_REPORTING);
            ageAtDiagnosis = testDataForMetforminScreener.get(MetforminScreenerConstants.AGE_AT_DIAGNOSIS);
            monthOfDiagnosis = testDataForMetforminScreener.get(MetforminScreenerConstants.MONTH_OF_DIAGNOSIS);
            yearOfDiagnosis = testDataForMetforminScreener.get(MetforminScreenerConstants.YEAR_OF_DIAGNOSIS);
            areYouTheParticipantCurrentlyReceivingTreatment = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_THE_PARTICIPANT_CURRENTLY_RECEIVING_TREATMENT);
            pleaseProvideTheNameOfTheInstitutionWhereTheCancerWasDiagnosed = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_PROVIDE_THE_NAME_OF_THE_INSTITUTION_WHERE_THE_CANCER_WAS_DIAGNOSED);
            pleaseProvideTheNameOfTheInstitutionWhereTheCancerWasTreated = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_PROVIDE_THE_NAME_OF_THE_INSTITUTION_WHERE_THE_CANCER_WAS_TREATED);
            pleaseProvideTheNameOfTheTreatingPhysician = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_PROVIDE_THE_NAME_OF_THE_TREATING_PHYSICIAN);
            additionalDetails = testDataForMetforminScreener.get(MetforminScreenerConstants.ADDITIONAL_DETAILS);
            haveYouTheParticipantHadSurgeryToRemoveCancerLast3Months = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_HAD_SURGERY_TO_REMOVE_CANCER_LAST_3_MONTHS);
            pleaseProvideTheDateOfSurgery = testDataForMetforminScreener.get(MetforminScreenerConstants.PLEASE_PROVIDE_THE_DATE_OF_SURGERY);
            haveYouTheParticipantReceivedChemotherapyOrRadiationLast6Months = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_RECEIVED_CHEMOTHERAPY_OR_RADIATION_LAST_6_MONTHS);
            whatWasTheDateOfParticipantLastTreatment = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_WAS_THE_DATE_OF_PARTICIPANT_LAST_TREATMENT);
            areYouTheParticipantCurrentlyUndergoingTreatmentForCancer = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_THE_PARTICIPANT_CURRENTLY_UNDERGOING_TREATMENT_FOR_CANCER);
            listAllMedicationsAndSeparateWithASemicolon = testDataForMetforminScreener.get(MetforminScreenerConstants.LIST_ALL_MEDICATIONS_AND_SEPARATE_WITH_A_SEMICOLON);
            doYouTheParticipantHaveAKnownAllergyToMetformin = testDataForMetforminScreener.get(MetforminScreenerConstants.DO_YOU_THE_PARTICIPANT_HAVE_A_KNOWN_ALLERGY_TO_METFORMIN);
            haveYouTheParticipantTakenMetforminForMoreThan3MonthsInTotal = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_TAKEN_METFORMIN_FOR_MORE_THAN_3_MONTHS_IN_TOTAL);
            haveYouTheParticipantEverTakenMetformin = testDataForMetforminScreener.get(MetforminScreenerConstants.HAVE_YOU_THE_PARTICIPANT_EVER_TAKEN_METFORMIN);
            areYouTheParticipantCurrentlyTakingMetformin = testDataForMetforminScreener.get(MetforminScreenerConstants.ARE_YOU_THE_PARTICIPANT_CURRENTLY_TAKING_METFORMIN);
            howDidYouTheParticipantHearAboutThisStudy = testDataForMetforminScreener.get(MetforminScreenerConstants.HOW_DID_YOU_THE_PARTICIPANT_HEAR_ABOUT_THIS_STUDY);
            hereAreAFewRemainingQuestionsRegardingThisStudy = testDataForMetforminScreener.get(MetforminScreenerConstants.HERE_ARE_A_FEW_REMAINING_QUESTIONS_REGARDING_THIS_STUDY);
            name = testDataForMetforminScreener.get(MetforminScreenerConstants.NAME);
            address = testDataForMetforminScreener.get(MetforminScreenerConstants.ADDRESS);
            medicalPhoneNumber = testDataForMetforminScreener.get(MetforminScreenerConstants.MEDICAL_PHONE_NUMBER);
            doWeHaveYourTheParticipantsPermissionToCallThisIndividualToSeekMoreInformation = testDataForMetforminScreener.get(MetforminScreenerConstants.DO_WE_HAVE_YOUR_THE_PARTICIPANTS_PERMISSION_TO_CALL_THIS_INDIVIDUAL_TO_SEEK_MORE_INFORMATION);
            whatAreTheMainReasonsForParticipatingInThisStudySelectAllThatApply = testDataForMetforminScreener.get(MetforminScreenerConstants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_IN_THIS_STUDY_SELECT_ALL_THAT_APPLY);
            receiveGeneticTesting = testDataForMetforminScreener.get(MetforminScreenerConstants.RECEIVE_GENETIC_TESTING);
            submit_Screen_text1 = testDataForMetforminScreener.get(MetforminScreenerConstants.SUBMIT_SCREEN_TEXT1);
            submit_Screen_text2 = testDataForMetforminScreener.get(MetforminScreenerConstants.SUBMIT_SCREEN_TEXT2);
            submit_Screen_text3 = testDataForMetforminScreener.get(MetforminScreenerConstants.SUBMIT_SCREEN_TEXT3);
            OK = testDataForMetforminScreener.get(MetforminScreenerConstants.OK);
            proxyFirstName = testDataForMetforminScreener.get(MetforminScreenerConstants.PROXY_FIRST_NAME);
            proxyMiddleInitial = testDataForMetforminScreener.get(MetforminScreenerConstants.PROXY_MIDDLE_INITIAL);
            proxyLastName = testDataForMetforminScreener.get(MetforminScreenerConstants.PROXY_LAST_NAME);
        }
    }
}