package PLATFORM_BUSINESS.OFFBOARD.constants;

public class CBIIT_OFFBOARD_FORM_Constants {

    /* CBIIT OFFBOARD TEXT PAGE TITLE  */
    public static final String CBIIT_OFFBOARD_TEXT_PAGE_TITLE = "CBIIT Offboarding";

    /* CATEGORY TEXT */
    public static String CATEGORY_TEXT = "Category";

    /* CBIIT BIZ SERVICES LINK */
    public static String CBIIT_BUSINESS_SERVICESLINK = "CBIIT Business Services";

    /* CBIIT OFFBOARD PAGE LINK TEXT */
    public static String CBIIT_OFFBOARD_PAGE_LINK_TEXT = "CBIIT Offboarding Employee";

    /* CBIIT OFFBOARD REQUESTED FOR NAME */
    public static String CBIIT_OFFBOARD_REQUESTED_FOR_NAME = "Ben Foulkes";

    /* CBIIT OFFBOARD REQUESTED FOR NON-NIH EMAIL */
    public static String CBIIT_OFFBOARD_REQUESTED_FOR_NON_NIH_EMAIL = "Testemail@gmail.com";

    /* CBIIT OFFBOARD FORM ENTER KEY */
    public static String CBIIT_OFFBOARD_FORM_ENTER_KEY = "Enter";

    /* CBIIT OFFBOARD FORM YES OPTION SELECTED */
    public static String CBIIT_OFFBOARD_FORM_YES_OPTION_SELECTED = "Yes";

    /* CBIIT OFFBOARD FORM NO OPTION SELECTED */
    public static String CBIIT_OFFBOARD_FORM_NO_OPTION_SELECTED = "No";

    /* CBIIT OFFBOARD FORM OK OPTION SELECTED */
    public static String CBIIT_OFFBOARD_FORM_OK_OPTION_SELECTED = "OK";

    /* CBIIT OFFBOARD PHONE NUMBER ENTERED */
    public static String CBIIT_OFFBOARD_PHONE_NUMBER_ENTERED = "1223334444";

    /* CBIIT OFFBOARDING BEFORE 5 PM TEXT  */
    public static String CBIIT_OFFBOARDING_BEFORE_FIVE_PM_TEXT = "Offboarding before 5:00 PM";

    /* CBIIT 'DATE & TIME OF OFFBOARDING' FIELD TEXT  */
    public static String CBIIT_DATE_AND_TIME_OF_OFFBOARDING_FIELD_TEXT = "Date & Time of Offboarding";

    /* CBIIT OFFBOARD POINT OF CONTACT NAME */
    public static String CBIIT_OFFBOARD_POINT_OF_CONTACT_NAME = "Aaron Bonnell";

    /* CBIIT OFFBOARDING EMPLYEE ADDRESS FIELD TEXT  */
    public static String CBIIT_OFFBOARDING_EMPLOYEE_ADDRESS_FIELD_TEXT = "Employee Address";

    /* CBIIT OFFBOARDING FEDEX LABEL NEEDED FIELD TEXT  */
    public static String CBIIT_OFFBOARDING_FEDEX_LABEL_NEEDED_FIELD_TEXT = "^FedEx Label Needed$";

    /* CBIIT OFFBOARDING FEDEX LABEL NEEDED TEXT  */
    public static String CBIIT_OFFBOARDING_FEDEX_LABEL_NEEDED_TEXT = "FedEx Label Needed";

    /* CBIIT OFFBOARD ADDRESS ENTERED */
    public static String CBIIT_OFFBOARD_ADDRESS_ENTERED = "123 Test Ave";

    /* CBIIT OFFBOARDING ARE BOXES NEEDED FOR ITEMS TO BE RETURNED FIELD TEXT  */
    public static String CBIIT_OFFBOARDING_ARE_BOXES_NEEDED_FOR_ITEMS_TO_BE_RETURNED_FIELD_TEXT = "^Are Boxes Needed for Items to be returned\\?$";

    /* CBIIT OFFBOARDING ARE BOXES NEEDED FOR ITEMS TO BE RETURNED TEXT  */
    public static String CBIIT_OFFBOARDING_ARE_BOXES_NEEDED_FOR_ITEMS_TO_BE_RETURNED_TEXT = "Are Boxes Needed for Items to be returned?";

    /* CBIIT OFFBOARDING NUMBER OF BOXES NEEDED? TEXT  */
    public static String CBIIT_OFFBOARDING_NUMBER_OF_BOXES_NEEDED_TEXT = "Number of Boxes Needed?";

    /* CBIIT OFFBOARDING NUMBER OF BOXES NEEDED? TEXT BOX VALUE */
    public static String CBIIT_OFFBOARDING_NUMBER_OF_BOXES_NEEDED_TEXT_BOX_VALUE = "10";

    /* CBIIT OFFBOARDING HARDWARE RETURN TICKET ALREADY CREATED FIELD TEXT  */
    public static String CBIIT_OFFBOARDING_HARDWARE_RETURN_TICKET_ALREADY_CREATED_FIELD_TEXT = "^Hardware Return Ticket Already Created$";

    /* CBIIT OFFBOARDING HARDWARE RETURN TICKET NUMBER TEXT  */
    public static String CBIIT_OFFBOARDING_HARDWARE_RETURN_TICKET_NUMBER_TEXT = "Hardware Return Ticket Number(s)";

    /* CBIIT OFFBOARDING HARDWARE RETURN TICKET NUMBER(S) TEXT  */
    public static String CBIIT_OFFBOARDING_HARDWARE_RETURN_TICKET_NUMBER_S_TEXT = "Hardware Return Ticket Number(s)";

    /* CBIIT "DATE OF TRANSFER" TEXT  */
    public static String CBIIT_OFFBOARDING_DATE_OF_TRANSFER_TEXT = "Date of Transfer";

    /* CBIIT "HN/SAC CODE (TRANSFER TO)" TEXT  */
    public static String CBIIT_HN_SAC_CODE_TRANSFER_TO_TEXT = "HN/SAC Code (Transfer to)";

    /* CBIIT "HN/SAC CODE (TRANSFER TO)" TEXT BOX VALUE  */
    public static String CBIIT_HN_SAC_CODE_TRANSFER_TO_TEXT_BOX_Value = "Test Free Text field &^$%6";

    /* CBIIT 'ONSITE LOCATION' SELECTED DROP DOWN VALUE  */
    public static String CBIIT_ONSITE_LOCATION_SELECTED_DROP_DOWN_VALUE = "Pennsylvania";

    /* CBIIT 'RETURN HARDWARE FORM URL' TEXT  */
    public static String CBIIT_RETURN_HARDWARE_FORM_URL_TEXT = "Return Hardware Form URL";

    /* CBIIT 'REQUIRED' TEXT  */
    public static String CBIIT_REQUIRED_TEXT = "Required";

    /* SOME REQUIRED FIELDS ARE INCOMPLETE TEXT  */
    public static String CBIIT_REQUIRED_FIELDS_ARE_INCOMPLETE_TEXT = "Some fields are incomplete: Hardware Return Ticket Number(s)";

    /* MANDATORY FIELD */
    public static String MANDATORY_FIELD = "field.mandatory";
}