package ServiceNow.CHARMS.ScenariosData;

import ServiceNow.CHARMS.Constants.CHARMS_Data_File_Path_Constants;
import appsCommon.PageInitializers.PageInitializer;
import com.nci.automation.utils.ExcelReader;
import java.util.Map;

public class RAS_Screener_TestDataManager extends PageInitializer {

    /**
     * RAS SCREENER VARIABLES
     */
    public Map<String, String> TEST_DATA_FOR_RAS_SCREENER;
    public String ARE_YOU_COMPLETING_THIS_FORM_FOR_SOMEONE_ELSE_OR_YOURSELF;
    public String FIRST_NAME;
    public String middleInitial;
    public String lastName;
    public String whatIsYourDateOfBirth;
    public String dateOfBirthMonth;
    public String dateOfBirthYear;
    public String whatIsYourRelationshipToTheProband;
    public String areYouTheLegalGuardianOfTheProband;
    public String theNextSetOfQuestionsWillCollectBasicInformationAboutTheProband;
    public String sexAssignedAtBirthOption;
    public String areYouAdoptedOption;
    public String isTheProbandAlive;
    public String countryOption;
    public String street;
    public String street2;
    public String city;
    public String state;
    public String zipcode;
    public String emailAddress;
    public String emailAddressConfirm;
    public String homePhoneNumber;
    public String cellPhoneNumber;
    public String workPhoneNumber;
    public String whatIsYourEthnicity;
    public String whatIsYourRace;
    public String whatIsYourRaceOther;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_RASOPATHIES_NET_OPTION;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_FAMILY_ADVOCACY_GROUP_OPTION;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_OPTION;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_NOT_INVOLVED_IN_OTHER_STUDY;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_FAMILY_ADVOCACY_GROUP_TEXT_BOX;
    public String ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_TEXT_BOX;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_FEEDING_PROBLEMS_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_NEUROCOGNITIVE_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_SKELETAL_DEFORMITIES_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_HEAD_CRANIOFACIAL_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_EYE_EAR_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_SKIN_HAIR_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_HEART_PROBLEMS_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_GENITAL_ABNORMALITIES_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_NON_CANCEROUS_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_LYMPHEDEMA_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OTHER_OPTION;
    public String HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OTHER_OPTION_TEXT_BOX;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option1;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option2;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option3;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option4;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option1;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option2;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option3;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option4;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option1;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option2;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option3;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option4;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option1;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option2;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option3;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option4;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option1;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option2;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option3;
    public String pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option4;
    public String forWhichSpecificRASopathy;
    public String forWhichSpecificRASopathyOther;
    public String ageAtDiagnosis;
    public String yearOfDiagnosisRas;
    public String weKnowThatRASopathiesAreAGroup;
    public String areYouAParticipantInOtherStudyGroup;
    public String haveYouBeenDiagnosedWithFollowingConditions;
    public String haveYouBeenDiagnosedWithCancer;
    public String haveYouBeenDiagnosedWithARasopathy;
    public String haveAnyOfYourBiologicalRelativesBeenDiagnosedWithARasopathy;
    public String haveYouEverHadGeneticTesting;
    public String howDidYouHearAboutThisStudy;
    public String howDidYouHearAboutThisStudyOtherReason;
    public String haveYouOrOtherFamilyMembersParticipatedInOtherStudy;
    public String whatAreMainReasonsForParticipatingInStudy;
    public String whatAreMainReasonsForParticipatingInStudyOtherReason;
    public String whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyFirst;
    public String whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyMi;
    public String whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyLast;
    public String doYouHaveACopyOfTheGenetic;
    public String howWouldYouLikeToProvideTheGeneticTestResults;
    public String weWillNowAskAFewRemainingQuestionsRegarding;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option4;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option4;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option4;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option4;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option4;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option1;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option2;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option3;
    public String pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option4;
    public String whatAreTheMainReasonsForParticipatingOption1Other;
    public String whatAreTheMainReasonsForParticipatingOption2Other;
    public String whatAreTheMainReasonsForParticipatingOption3Other;
    public String whatAreTheMainReasonsForParticipatingOption4Other;
    public String whatAreTheMainReasonsForParticipatingOption1;
    public String whatAreTheMainReasonsForParticipatingOption2;
    public String whatAreTheMainReasonsForParticipatingOption3;
    public String whatAreTheMainReasonsForParticipatingOption4;
    public String youAreAlmostDone;

    public void dataInitializerRasScreener(String sheetName) {
        /**
         * FETCHING DATA FROM EXCEL BEFORE SUBMITTING SCREENER
         */
        if (sheetName.equals("screenerScenario1") || sheetName.equals("screenerScenario2")) {
            if(sheetName.equals("screenerScenario1")){
                TEST_DATA_FOR_RAS_SCREENER = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.RAS_SCENARIO_ONE_DATA, sheetName);
            }
            if(sheetName.equals("screenerScenario2")){
                TEST_DATA_FOR_RAS_SCREENER = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.RAS_SCENARIO_TWO_DATA, sheetName);
            }
            ARE_YOU_COMPLETING_THIS_FORM_FOR_SOMEONE_ELSE_OR_YOURSELF = TEST_DATA_FOR_RAS_SCREENER.get("Are you completing this form for someone else or for yourself?");
            FIRST_NAME = TEST_DATA_FOR_RAS_SCREENER.get("First name");
            middleInitial = TEST_DATA_FOR_RAS_SCREENER.get("Middle Initial");
            lastName = TEST_DATA_FOR_RAS_SCREENER.get("Last name");
            whatIsYourDateOfBirth = TEST_DATA_FOR_RAS_SCREENER.get("What is your date of birth?");
            dateOfBirthMonth = TEST_DATA_FOR_RAS_SCREENER.get("Date of birth month");
            dateOfBirthYear = TEST_DATA_FOR_RAS_SCREENER.get("Date of birth year");
            sexAssignedAtBirthOption = TEST_DATA_FOR_RAS_SCREENER.get("What was your sex assigned at birth?");
            areYouAdoptedOption = TEST_DATA_FOR_RAS_SCREENER.get("Are you adopted?");
            countryOption = TEST_DATA_FOR_RAS_SCREENER.get("In which country do you currently live?");
            street = TEST_DATA_FOR_RAS_SCREENER.get("Street");
            street2 = TEST_DATA_FOR_RAS_SCREENER.get("Street 2 (optional)");
            city = TEST_DATA_FOR_RAS_SCREENER.get("City");
            state = TEST_DATA_FOR_RAS_SCREENER.get("State (Abbreviation)");
            zipcode = TEST_DATA_FOR_RAS_SCREENER.get("Zip Code");
            emailAddress = TEST_DATA_FOR_RAS_SCREENER.get("What is your email address?");
            emailAddressConfirm = TEST_DATA_FOR_RAS_SCREENER.get("Please confirm your email address");
            homePhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get("Home phone number");
            cellPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get("Cell phone number");
            workPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get("Work phone number");
            whatIsYourEthnicity = TEST_DATA_FOR_RAS_SCREENER.get("What is your ethnicity?");
            whatIsYourRace = TEST_DATA_FOR_RAS_SCREENER.get("What is your race? Please select all that apply.");
            whatIsYourRaceOther = TEST_DATA_FOR_RAS_SCREENER.get("Race text box");
            areYouAParticipantInOtherStudyGroup = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group?  Please specify.");
            haveYouBeenDiagnosedWithFollowingConditions = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer.");
            haveYouBeenDiagnosedWithCancer = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with cancer?");
            haveYouBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get("Have you been diagnosed with a RASopathy such as Noonan syndrome, Noonan syndrome with multiple lentigines, Costello syndrome, cardiofaciocutaneous syndrome, Legius syndrome, capillary arteriovenous malformation syndrome, hereditary gingival fibromatosis or SYNGAP1 syndrome?");
            haveAnyOfYourBiologicalRelativesBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get("Have any of your biological relatives been diagnosed with a RASopathy?");
            haveYouEverHadGeneticTesting = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever had genetic testing?");
            howDidYouHearAboutThisStudy = TEST_DATA_FOR_RAS_SCREENER.get("How did you hear about this study?  If a specific health care provider referred you to this study, please include their name in the corresponding text box.");
            howDidYouHearAboutThisStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get("How did you hear about this study?  If a specific health care provider referred you to this study, please include their name in the corresponding text box. Other reason");
            haveYouOrOtherFamilyMembersParticipatedInOtherStudy = TEST_DATA_FOR_RAS_SCREENER.get("Have you or other family members ever participated in another study on RASopathies at another medical institution, university, government agency or other site?");
            whatAreMainReasonsForParticipatingInStudy = TEST_DATA_FOR_RAS_SCREENER.get("What are the main reasons for participating in this study?  Select all that apply.  Please elaborate on the reason in the corresponding textbox.");
            whatAreMainReasonsForParticipatingInStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get("What are the main reasons for participating in this study?  Select all that apply.  Please elaborate on the reason in the corresponding textbox. Other reason");
            youAreAlmostDone = TEST_DATA_FOR_RAS_SCREENER.get("You are almost done!");
            weKnowThatRASopathiesAreAGroup = TEST_DATA_FOR_RAS_SCREENER.get("We know that RASopathies are a group of syndromes that have a genetic basis.  In order to help us determine eligibility for the RASopathies Study, we also need to know about any genetic testing that has been completed.");
            weWillNowAskAFewRemainingQuestionsRegarding = TEST_DATA_FOR_RAS_SCREENER.get("We will now ask a few remaining questions regarding this study.");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_RASOPATHIES_NET_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? RASopathies Net option");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_FAMILY_ADVOCACY_GROUP_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? Family Advocacy Group option");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? Other option");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_NOT_INVOLVED_IN_OTHER_STUDY = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? I am not involved in any other research study or registry group option");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_FAMILY_ADVOCACY_GROUP_TEXT_BOX = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? Family Advocacy Group text box");
            ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_TEXT_BOX = TEST_DATA_FOR_RAS_SCREENER.get("Are you a participant in any other research study or registry group? Other text box");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_FEEDING_PROBLEMS_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Feeding Problems option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_NEUROCOGNITIVE_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Neurocognitive option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_SKELETAL_DEFORMITIES_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Skeletal Deformities option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_HEAD_CRANIOFACIAL_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Head/Craniofacial option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_EYE_EAR_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Eye/ear");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_SKIN_HAIR_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Skin/hair option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_HEART_PROBLEMS_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Heart problems option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_GENITAL_ABNORMALITIES_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Genital abnormalities option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_NON_CANCEROUS_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Non-Cancerous tumors option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_LYMPHEDEMA_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Lymphedema option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OTHER_OPTION = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Other option");
            HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OTHER_OPTION_TEXT_BOX = TEST_DATA_FOR_RAS_SCREENER.get("Have you ever been diagnosed with the following conditions?  Select all that apply.  If you do not see the exact condition diagnosed, please select the closest answer. Other option text box");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option1 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Cancer Type Option 1");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option2 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Cancer Type Option 2");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option3 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Cancer Type Option 3");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option4 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Cancer Type Option 4");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option1 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Other Cancer Option 1");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option2 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Other Cancer Option 2");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option3 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Other Cancer Option 3");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option4 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Other Cancer Option 4");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option1 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Age at diagnosis Option 1");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option2 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Age at diagnosis Option 2");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option3 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Age at diagnosis Option 3");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option4 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Age at diagnosis Option 4");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option1 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Year at diagnosis Option 1");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option2 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Year at diagnosis Option 2");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option3 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Year at diagnosis Option 3");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option4 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Year at diagnosis Option 4");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option1 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Currently receiving treatment Option 1");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option2 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Currently receiving treatment Option 2");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option3 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Currently receiving treatment Option 3");
            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option4 = TEST_DATA_FOR_RAS_SCREENER.get("Please complete the box below by selecting which primary cancers were diagnosed and at what age and year they occurred. If cancer spread from one place to another, please only indicate the original cancers and not the number of sites where cancer spread. Currently receiving treatment Option 4");
            forWhichSpecificRASopathy = TEST_DATA_FOR_RAS_SCREENER.get("For which specific RASopathy have you been diagnosed?");
            forWhichSpecificRASopathyOther = TEST_DATA_FOR_RAS_SCREENER.get("For which specific RASopathy have you been diagnosed? Other text box");
            ageAtDiagnosis = TEST_DATA_FOR_RAS_SCREENER.get("Age at diagnosis");
            yearOfDiagnosisRas = TEST_DATA_FOR_RAS_SCREENER.get("Year of diagnosis");
            haveYouEverHadGeneticTesting = TEST_DATA_FOR_RAS_SCREENER.get("Do you have a copy of the genetic test results?");
            howWouldYouLikeToProvideTheGeneticTestResults = TEST_DATA_FOR_RAS_SCREENER.get("How would you like to provide the genetic test results to us?  Please select one.  On the next page, you will be provided with where to send the information.");
            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_1);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_2);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_3);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_4);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_4);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_4);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_4);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_4);
            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_4);
            whatAreTheMainReasonsForParticipatingOption1Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_1);
            whatAreTheMainReasonsForParticipatingOption1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_1);
            whatAreTheMainReasonsForParticipatingOption2Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_2);
            whatAreTheMainReasonsForParticipatingOption2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_2);
            whatAreTheMainReasonsForParticipatingOption3Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_3);
            whatAreTheMainReasonsForParticipatingOption3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_3);
            whatAreTheMainReasonsForParticipatingOption4Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_4);
            whatAreTheMainReasonsForParticipatingOption4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_4);

//        }else if (sheetName.equals("screenerScenario3")) {
//            TEST_DATA_FOR_RAS_SCREENER = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.RAS_SCENARIO_THREE_DATA, sheetName);
//            areYouCompletingThisFormForSomeoneElseOrYourself = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_COMPLETING_THIS_FORM_FOR_SOMEONE_ELSE);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyFirst = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_FIRST);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyMi = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_MIDDLE);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyLast = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_LAST);
//            firstName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.FIRST_NAME);
//            middleInitial = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.MIDDLE_INITIAL);
//            lastName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.LAST_NAME);
//            whatIsYourRelationshipToTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RELATIONSHIP_TO);
//            areYouTheLegalGuardianOfTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_THE_LEGAL_GUARDIAN_OF_THE_PROBAND);
//            theNextSetOfQuestionsWillCollectBasicInformationAboutTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.THE_NEXT_SET_OF_QUESTIONS_WILL_COLLECT_BASIC_INFORMATION_ABOUT_THE_PROBAND);
//            whatIsYourDateOfBirth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_DATE_OF_BIRTH);
//            dateOfBirthMonth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_MONTH);
//            dateOfBirthYear = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_YEAR);
//            sexAssignedAtBirthOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.SEX_ASSIGNED_AT_BIRTH_OPTION);
//            areYouAdoptedOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_ADOPTED_OPTION);
//            isTheProbandAlive = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.IS_THE_PROBAND_ALIVE);
//            countryOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHICH_COUNTRY_DO_YOU_CURRENTLY_LIVE_IN_OPTION);
//            street = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_ADDRESS);
//            street2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_2_ADDRESS);
//            city = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CITY_TEXT);
//            state = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STATE_TEXT);
//            zipcode = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ZIP_CODE_TEXT);
//            emailAddress = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.EMAIL_ADDRESS);
//            emailAddressConfirm = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CONFIRM_EMAIL_ADDRESS);
//            homePhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOME_PHONE_NUMBER);
//            cellPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CELL_PHONE_NUMBER);
//            workPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WORK_PHONE_NUMBER);
//            whatIsYourEthnicity = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_ETHNICITY);
//            whatIsYourRace = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RACE);
//            toDetermineEligibilityForThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.TO_DETERMINE_ELIGIBILITY_FOR_THIS_STUDY);
//            areYouAParticipantInOtherStudyGroup = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_A_PARTICIPANT_IN_OTHER_STUDY_GROUP);
//            haveYouBeenDiagnosedWithFollowingConditions = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS);
//            haveYouBeenDiagnosedWithCancer = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_CANCER);
//            haveYouBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_BEEN_DIAGNOSED_WITH_A_RASOPATHY);
//            haveAnyOfYourBiologicalRelativesBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_ANY_BIOLOGICAL_RELATIVES_BEEN_DIAGNOSED_WITH_ARASOPATHY);
//            haveYouEverHadGeneticTesting = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_HAD_GENETIC_TESTING);
//            howDidYouHearAboutThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY);
//            howDidYouHearAboutThisStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY_OTHER_REASON);
//            haveYouOrOtherFamilyMembersParticipatedInOtherStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_OR_OTHER_FAMILY_MEMBERS_PARTICIPATED_IN_OTHER_STUDY);
//            whatAreMainReasonsForParticipatingInStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_IN_THIS_STUDY);
//            whatAreMainReasonsForParticipatingInStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_IN_THIS_STUDY_OTHER_REASON);
//            weKnowThatRASopathiesAreAGroup = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_KNOW_THAT_RASOPATHIES_ARE_A_GROUP);
//            weWillNowAskAFewRemainingQuestionsRegarding = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_WILL_NOW_ASK_A_FEW_REMAINING_QUESTIONS_REGARDING);
//            youAreAlmostDone = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.YOU_ARE_ALMOST_DONE);
//        }else if (sheetName.equals("screenerScenario4")) {
//            TEST_DATA_FOR_RAS_SCREENER = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.RAS_SCENARIO_FOUR_DATA, sheetName);
//            areYouCompletingThisFormForSomeoneElseOrYourself = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_COMPLETING_THIS_FORM_FOR_SOMEONE_ELSE);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyFirst = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_FIRST);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyMi = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_MIDDLE);
//            whatIsTheNameOfThePersonWhoMayBeEligibleForThisStudyLast = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_THE_NAME_OF_THE_PERSON_WHO_MAY_BE_ELIGIBLE_FOR_THIS_STUDY_LAST);
//            firstName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.FIRST_NAME);
//            middleInitial = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.MIDDLE_INITIAL);
//            lastName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.LAST_NAME);
//            whatIsYourRelationshipToTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RELATIONSHIP_TO);
//            areYouTheLegalGuardianOfTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_THE_LEGAL_GUARDIAN_OF_THE_PROBAND);
//            theNextSetOfQuestionsWillCollectBasicInformationAboutTheProband = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.THE_NEXT_SET_OF_QUESTIONS_WILL_COLLECT_BASIC_INFORMATION_ABOUT_THE_PROBAND);
//            whatIsYourDateOfBirth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_DATE_OF_BIRTH);
//            dateOfBirthMonth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_MONTH);
//            dateOfBirthYear = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_YEAR);
//            sexAssignedAtBirthOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.SEX_ASSIGNED_AT_BIRTH_OPTION);
//            areYouAdoptedOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_ADOPTED_OPTION);
//            isTheProbandAlive = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.IS_THE_PROBAND_ALIVE);
//            countryOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHICH_COUNTRY_DO_YOU_CURRENTLY_LIVE_IN_OPTION);
//            street = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_ADDRESS);
//            street2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_2_ADDRESS);
//            city = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CITY_TEXT);
//            state = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STATE_TEXT);
//            zipcode = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ZIP_CODE_TEXT);
//            emailAddress = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.EMAIL_ADDRESS);
//            emailAddressConfirm = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CONFIRM_EMAIL_ADDRESS);
//            homePhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOME_PHONE_NUMBER);
//            cellPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CELL_PHONE_NUMBER);
//            workPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WORK_PHONE_NUMBER);
//            whatIsYourEthnicity = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_ETHNICITY);
//            whatIsYourRace = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RACE);
//            whatIsYourRaceOther = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RACE_OTHER);
//            isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_RASOPATHIES_NET_OPTION);
//            isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_OPTION);
//          //  isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.IS_THE_PROBAND_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OPTION_3);
//           // isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.IS_THE_PROBAND_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OPTION_4);
//           // isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption2Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.IS_THE_PROBAND_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OPTION_2_OTHER);
//            isTheProbandAParticipantInAnyOtherResearchStudyOrRegistryGroupOption3Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_A_PARTICIPANT_IN_ANY_OTHER_RESEARCH_STUDY_OR_REGISTRY_GROUP_OTHER_TEXT_BOX);
//            toDetermineEligibilityForThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.TO_DETERMINE_ELIGIBILITY_FOR_THIS_STUDY);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_1);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_2);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_3);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_4);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption5 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_5);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption6 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_6);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption7 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_7);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption8 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_8);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption9 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_9);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption10 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_10);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption11 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_11);
//            haveYouEverBeenDiagnosedWithTheFollowingConditionsOption11Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS_OPTION_11_OTHER);
//            haveYouBeenDiagnosedWithCancer = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_CANCER);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_1_OPTION_1);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_1_OPTION_2);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_1_OPTION_3);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn1Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_1_OPTION_4);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_2_OPTION_1);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_2_OPTION_2);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_2_OPTION_3);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn2Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_2_OPTION_4);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_3_OPTION_1);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_3_OPTION_2);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_3_OPTION_3);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn3Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_3_OPTION_4);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_4_OPTION_1);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_4_OPTION_2);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_4_OPTION_3);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn4Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_4_OPTION_4);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_5_OPTION_1);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_5_OPTION_2);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_5_OPTION_3);
//            pleaseCompleteTheBoxBelowBySelectingWhichPrimaryCancersColumn5Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_COMPLETE_THE_BOX_BELOW_BY_SELECTING_WHICH_PRIMARY_CANCERS_COLUMN_5_OPTION_4);
//            haveYouBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_BEEN_DIAGNOSED_WITH_A_RASOPATHY);
//            forWhichSpecificRASopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.FOR_WHICH_SPECIFIC_RASOPATHY);
//            forWhichSpecificRASopathyOther = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.FOR_WHICH_SPECIFIC_RASOPATHY_OTHER);
//            ageAtDiagnosis = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.AGE_AT_DIAGNOSIS);
//            yearOfDiagnosisRas = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.YEAR_OF_DIAGNOSIS_RAS);
//            weKnowThatRASopathiesAreAGroup = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_KNOW_THAT_RASOPATHIES_ARE_A_GROUP);
//            haveAnyOfYourBiologicalRelativesBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_ANY_BIOLOGICAL_RELATIVES_BEEN_DIAGNOSED_WITH_ARASOPATHY);
//            haveYouEverHadGeneticTesting = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_HAD_GENETIC_TESTING);
//            howDidYouHearAboutThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY);
//            howDidYouHearAboutThisStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY_OTHER_REASON);
//            haveYouOrOtherFamilyMembersParticipatedInOtherStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_OR_OTHER_FAMILY_MEMBERS_PARTICIPATED_IN_OTHER_STUDY);
//            doYouHaveACopyOfTheGenetic = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DO_YOU_HAVE_A_COPY_OF_THE_GENETIC);
//            howWouldYouLikeToProvideTheGeneticTest = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_WOULD_YOU_LIKE_TO_PROVIDE_THE_GENETIC_TEST);
//            weWillNowAskAFewRemainingQuestionsRegarding = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_WILL_NOW_ASK_A_FEW_REMAINING_QUESTIONS_REGARDING);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn1Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_1_OPTION_4);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn2Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_2_OPTION_4);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn3Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_3_OPTION_4);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn4Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_4_OPTION_4);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn5Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_5_OPTION_4);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_1);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_2);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_3);
//            pleaseProvideTheInformationRegardingPreviousParticipationColumn6Option4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.PLEASE_PROVIDE_THE_INFORMATION_REGARDING_PREVIOUS_PARTICIPATION_COLUMN_6_OPTION_4);
//            whatAreTheMainReasonsForParticipatingOptin1Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_1);
//            whatAreTheMainReasonsForParticipatingOptin2Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_2);
//            whatAreTheMainReasonsForParticipatingOptin3Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_3);
//            whatAreTheMainReasonsForParticipatingOptin4Other = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_OPTION_4);
//            whatAreTheMainReasonsForParticipatingOptin1 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_1);
//            whatAreTheMainReasonsForParticipatingOptin2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_2);
//            whatAreTheMainReasonsForParticipatingOptin3 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_3);
//            whatAreTheMainReasonsForParticipatingOptin4 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_4);
//            youAreAlmostDone = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.YOU_ARE_ALMOST_DONE);
//        }if (sheetName.equals("screenerScenario5")) {
//            TEST_DATA_FOR_RAS_SCREENER = ExcelReader.excelIntoHashMap(CHARMS_Data_File_Path_Constants.RAS_SCENARIO_FIVE_DATA, sheetName);
//            areYouCompletingThisFormForSomeoneElseOrYourself = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_COMPLETING_THIS_FORM_FOR_SOMEONE_ELSE);
//            firstName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.FIRST_NAME);
//            middleInitial = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.MIDDLE_INITIAL);
//            lastName = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.LAST_NAME);
//            whatIsYourDateOfBirth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_DATE_OF_BIRTH);
//            dateOfBirthMonth = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_MONTH);
//            dateOfBirthYear = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.DATE_OF_BIRTH_YEAR);
//            sexAssignedAtBirthOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.SEX_ASSIGNED_AT_BIRTH_OPTION);
//            areYouAdoptedOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_ADOPTED_OPTION);
//            countryOption = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHICH_COUNTRY_DO_YOU_CURRENTLY_LIVE_IN_OPTION);
//            street = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_ADDRESS);
//            street2 = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STREET_2_ADDRESS);
//            city = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CITY_TEXT);
//            state = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.STATE_TEXT);
//            zipcode = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ZIP_CODE_TEXT);
//            emailAddress = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.EMAIL_ADDRESS);
//            emailAddressConfirm = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CONFIRM_EMAIL_ADDRESS);
//            homePhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOME_PHONE_NUMBER);
//            cellPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.CELL_PHONE_NUMBER);
//            workPhoneNumber = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WORK_PHONE_NUMBER);
//            whatIsYourEthnicity = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_ETHNICITY);
//            whatIsYourRace = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_IS_YOUR_RACE);
//            areYouAParticipantInOtherStudyGroup = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.ARE_YOU_A_PARTICIPANT_IN_OTHER_STUDY_GROUP);
//            haveYouBeenDiagnosedWithFollowingConditions = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_BEEN_DIAGNOSED_WITH_THE_FOLLOWING_CONDITIONS);
//            haveYouBeenDiagnosedWithCancer = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_BEEN_DIAGNOSED_WITH_CANCER);
//            haveYouBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_BEEN_DIAGNOSED_WITH_A_RASOPATHY);
//            haveAnyOfYourBiologicalRelativesBeenDiagnosedWithARasopathy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_ANY_BIOLOGICAL_RELATIVES_BEEN_DIAGNOSED_WITH_ARASOPATHY);
//            haveYouEverHadGeneticTesting = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_EVER_HAD_GENETIC_TESTING);
//            howDidYouHearAboutThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY);
//            howDidYouHearAboutThisStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HOW_DID_YOU_HEAR_ABOUT_THIS_STUDY_OTHER_REASON);
//            haveYouOrOtherFamilyMembersParticipatedInOtherStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.HAVE_YOU_OR_OTHER_FAMILY_MEMBERS_PARTICIPATED_IN_OTHER_STUDY);
//            whatAreMainReasonsForParticipatingInStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_IN_THIS_STUDY);
//            whatAreMainReasonsForParticipatingInStudyOtherReason = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WHAT_ARE_THE_MAIN_REASONS_FOR_PARTICIPATING_IN_THIS_STUDY_OTHER_REASON);
//            youAreAlmostDone = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.YOU_ARE_ALMOST_DONE);
//            toDetermineEligibilityForThisStudy = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.TO_DETERMINE_ELIGIBILITY_FOR_THIS_STUDY);
//            weKnowThatRASopathiesAreAGroup = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_KNOW_THAT_RASOPATHIES_ARE_A_GROUP);
//            weWillNowAskAFewRemainingQuestionsRegarding = TEST_DATA_FOR_RAS_SCREENER.get(ras_Screener_Constants.WE_WILL_NOW_ASK_A_FEW_REMAINING_QUESTIONS_REGARDING);
        }
    }
}