#---------------------Jenkins Execution Info-----------------------------------
#env=test
#browser=chrome
#Username=USER_VAR
#Password=PASSWORD_VAR
#headless=true
#setSlowMoTime=1000
#SideDoorUsername=CBIITTestAccount
#SideDoorPassword=VGVzdGVyMTIzQA==

env=test
browser=chrome
Username=juarezds
Password=QXZlbmdlcnNhc3NlbWJsZTk5Pw==
headless=true
setSlowMoTime=800
#SIDEDOOR TEST ACCOUNT
SideDoorUsername=CBIITTestAccount
SideDoorPassword=VGVzdGVyMTIzQA==

#---------------------Waits Info-------------------------------------
#--------------------------------------------------------------------
implicitWaitInSeconds=80
explicitWaitInSeconds=100
pageLoadTimeoutInSeconds=30
takeScreenShots=true
implicitWaitInSecondsExpedited=80

#--------------------------Other Info---------------------------------
#---------------------------------------------------------------------
logLevel=debug
