name: ANALYSIS-TOOLS-CCP-Regression

on:
  schedule:
    # This corresponds to 10:00 AM EST (3:00 PM UTC) from Monday to Friday
    - cron: '0 15 * * MON-FRI'
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: NCI-WINDOWS
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run specific runner class
        run: mvn -B -q -Dtest="AnalysisTools.CervicalCP.CervicalCPRunners.RunCervicalCPRegressionTest" test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        run: |
          $timeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
          $dateTime = [System.TimeZoneInfo]::ConvertTime([System.DateTime]::UtcNow, $timeZone)
          $timestamp = $dateTime.ToString("yyyy-MM-dd_hh-mm-ss_tt")
          Add-Content -Path $env:GITHUB_ENV -Value "timestamp=$timestamp"
      - name: Determine report path
        id: reportpath
        run: echo "path=html-CCP-reports" >> $GITHUB_ENV

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CCP-REGRESSION-${{ env.timestamp }}
          path: target/CCP-reports/*