name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    strategy:
      matrix:
        env: ['test']
        browser: ['chrome', 'firefox', 'safari']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set environment variables
        run: |
          mvn test -DUsername='${{ secrets.SIDEDOORPASSWORD }}' -DPassword='${{ secrets.SIDEDOORUSERNAME }}' -Dbrowser='${{ matrix.browser }}' -Denv='${{ matrix.env }}'

      - name: Run specific runner class
        run: mvn -Dtest=SSJ_Progression_Runners test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/report.json


  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set environment variables
        run: |
          mvn test -DUsername='${{ secrets.SIDEDOORPASSWORD }}' -DPassword='${{ secrets.SIDEDOORUSERNAME }}' -Dbrowser='${{ github.event.inputs.testBrowser }}' -Denv='test'

      - name: Run specific runner class
        run: mvn -Dtest=SSJ_Progression_Runners test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/report.json