name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['test']
        browser: ['chrome', 'firefox', 'safari']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set environment variables
        run: |
          echo "Username=${{ secrets.SIDEDOORPASSWORD }}" >> $GITHUB_ENV
          echo "Password=${{ secrets.SIDEDOORUSERNAME }}" >> $GITHUB_ENV
          echo "browser=${{ matrix.browser }}" >> $GITHUB_ENV
          echo "env=${{ matrix.env }}" >> $GITHUB_ENV

      - name: Run specific runner class
        run: mvn -Dtest=SSJ_Progression_Runners test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/report.json
