name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set environment variables
        run: |
          echo "Username=${{ secrets.SIDEDOORPASSWORD }}" >> $GITHUB_ENV
          echo "Password=${{ secrets.SIDEDOORUSERNAME }}" >> $GITHUB_ENV
          echo "browser=chrome" >> $GITHUB_ENV
          echo "env=test" >> $GITHUB_ENV

      - name: Run specific runner class
        run: mvn -Dtest=SSJ_Progression_Runners

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
