name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    strategy:
      matrix:
        env: ['test']
        browser: ['chrome', 'firefox', 'safari']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set environment variables
        run: |
          echo "Username=${{ secrets.SIDEDOORPASSWORD }}" >> $GITHUB_ENV
          echo "Password=${{ secrets.SIDEDOORUSERNAME }}" >> $GITHUB_ENV
          echo "browser=${{ matrix.browser }}" >> $GITHUB_ENV
          echo "env=${{ matrix.env }}" >> $GITHUB_ENV
          echo "isCloud=true" >> $GITHUB_ENV
          echo "Headless=true" >> $GITHUB_ENV

      - name: Print environment variables
        run: echo $isCloud $Username $Password $Browser $Env

      - name: Run specific runner class
        run: mvn -B -Dtest=SSJ_Progression_Runners test
        continue-on-error: true

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report
          path: target/cucumber.json

  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set environment variables
        run: |
          echo "Username=${{ secrets.SIDEDOORPASSWORD }}" >> $GITHUB_ENV
          echo "Password=${{ secrets.SIDEDOORUSERNAME }}" >> $GITHUB_ENV
          echo "browser=${{ github.event.inputs.testBrowser }}" >> $GITHUB_ENV
          echo "env=test" >> $GITHUB_ENV
          echo "isCloud=true" >> $GITHUB_ENV

      - name: Print environment variables
        run: echo $isCloud $Username $Password $Browser $Env

      - name: Run specific runner class
        run: mvn -B clean install -Dtest=SSJ_Progression_Runners test
        continue-on-error: true

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report
          path: target/html-reports/*

      - name: Push HTML Report
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "diegojuarezbusiness@gmail.com"
          git config --global user.name "iamdez99"
          git checkout -b gh-pages
          mv target/html-reports/cucumber-default-report.html .  # Move HTML report to root
          git add .
          git commit -m "Publishing cucumber report"
          git push -f https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages