name: PLATFORM BUSINESS - NERD SMOKE TESTS

on:
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'
jobs:
  build:
    runs-on: NCI-WINDOWS
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run specific runner class
        shell: cmd
        run: mvn -B -q -Dtest=Run_NERD_Smoke_Test test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        shell: cmd
        run: echo "::set-output name=timestamp::%date:~-4,4%-%date:~-10,2%-%date:~-7,2%_%time:~0,2%-%time:~3,2%-%time:~6,2%"

      - name: Determine report path
        id: reportpath
        shell: cmd
        run: echo "::set-output name=path::nerd-smoke-reports"

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report-${{ github.run_number }}
          path: target/nerd-smoke-reports/*

      - name: Push HTML Report
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "diegojuarezbusiness@gmail.com"
          git config --global user.name "iamdez99"
          git stash
          git fetch
          git checkout gh-pages
          git rm -f src/main/resources/conf/cloudEnv.properties
          git checkout stash -- .
          mkdir -p ${{ steps.reportpath.outputs.path }}
          mv target/nerd-smoke-reports/*.html ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html
          git add .
          git commit -m "Publishing cucumber report ${{ github.run_number }}"
          git push -f https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages

      - name: Update Test Results and Append to Index File
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ -f "nerd-smoke-test-results.html" ]]; then
            sed -i 's/<h1>.*<\/h1>/<h1>NERD Smoke Test Results<\/h1>/' nerd-smoke-test-results.html
            echo "<h3><a href='${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>" >> nerd-smoke-test-results.html
            git add nerd-smoke-test-results.html
            git commit -m "Update nerd-smoke-test-results.html"
          else
            echo "<h1>NERD Smoke Test Results</h1>" > nerd-smoke-test-results.html
            echo "<h3><a href='${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>" >> nerd-smoke-test-results.html
            git add nerd-smoke-test-results.html
            git commit -m "Create and update nerd-smoke-test-results.html"
          fi
          git push https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages