name: PLATFORM BUSINESS - SSJ REGRESSION TESTS

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * MON-FRI' # 7:15 AM EST (12:15 PM UTC) Monday to Friday

jobs:
  build:
    runs-on: NCI-WINDOWS
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run specific runner class
        shell: cmd
        run: mvn -B -q -Dtest=SSJ_Regression_Runners test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        shell: powershell
        run: |
          $timeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
          $dateTime = [System.TimeZoneInfo]::ConvertTime([System.DateTime]::UtcNow, $timeZone)
          $timestamp = $dateTime.ToString("yyyy-MM-dd_hh-mm-ss_tt")
          Add-Content -Path $env:GITHUB_ENV -Value "timestamp=$timestamp"

      - name: Determine report path
        id: reportpath
        shell: cmd
        run: echo "::set-output name=path::ssj-regression-reports"

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report-${{ env.timestamp }}
          path: target/ssj-regression-reports/*

      - name: Upload to SharePoint
        shell: powershell
        run: |
          $Env:PATH = "C:\Users\juarezds\AppData\Local\Programs\Python\Python312;$Env:PATH"
          python $Env:GITHUB_WORKSPACE\.github\scripts\upload_to_sharepoint.py
        env:
          FILES_PATH: target/ssj-regression-reports/*
          SHAREPOINT_SITE_ID: ${{ secrets.SHAREPOINT_SITE_ID }}
          SHAREPOINT_DRIVE_ID: ${{ secrets.SHAREPOINT_DRIVE_ID }}
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          client_secret: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          timestamp: ${{ env.timestamp }}
          UPLOAD_FOLDER: "Platform Business Applications/TEST AUTOMATION REPORTS/SSJ"