name: POWER BI - TEST

on:
  schedule:
    - cron: '45 13 * * MON-FRI' # Scheduled execution
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: NCI-WINDOWS  # Custom runner

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # Step 2: Run specific runner class
      - name: Run CHARMS Regression Test
        run: mvn -B -q -Dtest="CHARMS.runners.Run_CHARMS_RAS_Regression_Test" test
        continue-on-error: true

      # Step 3: Generate timestamp
      - name: Generate timestamp
        id: timestamp
        run: |
          $timeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
          $dateTime = [System.TimeZoneInfo]::ConvertTime([System.DateTime]::UtcNow, $timeZone)
          $timestamp = $dateTime.ToString("yyyy-MM-dd_hh-mm-ss_tt")
          Add-Content -Path $env:GITHUB_ENV -Value "timestamp=$timestamp"

      # Step 4: Determine report path
      - name: Determine report path
        id: reportpath
        run: echo "path=CHARMS-rasopathy-regression-reports" >> $GITHUB_ENV

      # Step 5: Generate Excel Report after the tests
      - name: Generate Excel File
        run: >
          mvn clean test \
          -DjsonFile="target/CHARMS-RAS-Regression-Test-Results.json" \
          -DexcelFile="target/CHARMS-Regression-Test-Results.xlsx"

      # Step 6: Upload Cucumber Report (HTML & others)
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CHARMS-RAS-REGRESSION-${{ env.timestamp }}
          path: target/CHARMS-rasopathy-regression-reports/*

      # New Step: Upload Excel File as Artifact
      - name: Upload Excel Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: CHARMS-RAS-REGRESSION-EXCEL-${{ env.timestamp }}
          path: target/CHARMS-Regression-Test-Results.xlsx

      # Step 7: Upload Reports and Excel to SharePoint
      - name: Upload to SharePoint
        shell: powershell
        run: |
          $Env:PATH = "C:\Users\juarezds\AppData\Local\Programs\Python\Python312;$Env:PATH"
          python $Env:GITHUB_WORKSPACE\.github\scripts\upload_to_sharepoint.py
        env:
          FILES_PATH: target/CHARMS-rasopathy-regression-reports/*
          SHAREPOINT_SITE_ID: ${{ secrets.SHAREPOINT_SITE_ID }}
          SHAREPOINT_DRIVE_ID: ${{ secrets.SHAREPOINT_DRIVE_ID }}
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          client_secret: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          timestamp: ${{ env.timestamp }}
          UPLOAD_FOLDER: 'Platform Scientific - CHARMS/TEST AUTOMATION REPORTS/Rasopathy'