name: Selenium 4 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable wget unzip
          CHROME_VERSION=`google-chrome-stable --version | awk -F "[ .]" '{print $3}'`
          echo "CHROME_VERSION="$CHROME_VERSION
          wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION -O LATEST_RELEASE
          VERSION=`cat LATEST_RELEASE`
          echo "VERSION="$VERSION
          wget https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run tests
        run: |
          mvn -Dtest=NERD_Progression_Test test