name: Run NERD Progression Tests

on:
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Replace variables in cloudEnv.properties
        run: |
          sed -i "s/SIDE_DOOR_USERNAME/${{ secrets.SIDEDOORUSERNAME }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/SIDE_DOOR_PASSWORD/${{ secrets.SIDEDOORPASSWORD }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/BROWSER_VAR/${{ github.event.inputs.testBrowser }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/ENV_VAR/test/g" src/main/resources/conf/cloudEnv.properties

      - name: Run specific runner class
        run: mvn -B -q -Dtest=Run_NERD_Progression_Test -DisCloud=true test
        continue-on-error: true

      - name: Determine report path
        id: reportpath
        run: echo "::set-output name=path::nerd-progression-reports-$(date +'%Y-%m-%d-at-%I-%M%P')"

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report-${{ github.run_number }}
          path: target/${{ steps.reportpath.outputs.path }}/*

      - name: Push HTML Report
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "diegojuarezbusiness@gmail.com"
          git config --global user.name "iamdez99"
          mkdir -p ${{ steps.reportpath.outputs.path }}
          mv target/nerd-progression-reports/*.html ${{ steps.reportpath.outputs.path }}/
          git add .
          git commit -m "Publishing cucumber report ${{ github.run_number }}"
          git push -f https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages

      - name: Update Test Results
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "<h3><a href='${{ steps.reportpath.outputs.path }}/nerd-progression-report.html'>Test Report ${{ steps.reportpath.outputs.path }}</a></h3>" >> nerd-progression-test-results.html
          git add nerd-progression-test-results.html 
          git commit -m "Update nerd-progression-test-results.html" 
          git push https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages