name: Selenium 4 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=`google-chrome-stable --version | cut -d ' ' -f3`
          echo "CHROME_VERSION="$CHROME_VERSION
          echo "CHROME_WE_DRIVER=http://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
          curl "http://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip" -O
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run tests
        run: |
          mvn -Dtest=NERD_Progression_Test test