name: PLATFORM BUSINESS - SSJ REGRESSION TESTS

on:
  workflow_dispatch:
  schedule:
    - cron: '45 12 * * 1-6' # 7:45 AM EST (12:45 PM UTC) Monday to Saturday

jobs:
  build:
    runs-on: NCI-WINDOWS
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run specific runner class
        shell: cmd
        run: mvn -B -q -Dtest=SSJ_Regression_Runners test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        shell: cmd
        run: echo "::set-output name=timestamp::%date:~-4,4%-%date:~-10,2%-%date:~-7,2%_%time:~0,2%-%time:~3,2%-%time:~6,2%"

      - name: Determine report path
        id: reportpath
        shell: cmd
        run: echo "::set-output name=path::ssj-regression-reports"

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report-${{ github.run_number }}-${{ steps.timestamp.outputs.timestamp }}
          path: target/ssj-regression-reports/*

      - name: Push HTML Report
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "dsjnih@gmail.com"
          git config --global user.name "iamdez99"
          git stash
          git fetch
          git checkout gh-pages
          git stash pop
          mkdir -p ssj-regression-reports
          mv target/ssj-regression-reports/*.html ssj-regression-reports/report-${{ steps.timestamp.outputs.timestamp }}.html
          git add .
          git commit -m "Publishing cucumber report ${{ github.run_number }} on ${{ steps.timestamp.outputs.timestamp }}"
          git push -f https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages

      - name: Update Test Results and Append to Index File
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ -f "ssj-regression-test-results.html" ]]; then
            sed -i 's/<h1>.*<\/h1>/<h1>SSJ Regression Test Results<\/h1>/' ssj-regression-test-results.html
            echo "<h3><a href='ssj-regression-reports/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ssj-regression-reports/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>" >> ssj-regression-test-results.html
            git add ssj-regression-test-results.html
            git commit -m "Update ssj-regression-test-results.html"
          else
            echo "<h1>SSJ Regression Test Results</h1>" > ssj-regression-test-results.html
            echo "<h3><a href='ssj-regression-reports/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ssj-regression-reports/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>" >> ssj-regression-test-results.html
            git add ssj-regression-test-results.html
            git commit -m "Create and update ssj-regression-test-results.html"
          fi
          git push https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages