name: PLATFORM BUSINESS - SSJ REGRESSION TESTS

on:
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'

jobs:
  build:
    runs-on: NCI-WINDOWS
    env:
      CI: 'true'
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Check the content of cloudEnv.properties
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Get-Content src/main/resources/conf/cloudEnv.properties
        shell: powershell

      - name: Replace variables in cloudEnv.properties
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          $content = Get-Content src/main/resources/conf/cloudEnv.properties
          $content = $content -replace 'SIDE_DOOR_USERNAME', '${{ secrets.SIDEDOORUSERNAME }}'
          $content = $content -replace 'SIDE_DOOR_PASSWORD', '${{ secrets.SIDEDOORPASSWORD }}'
          $content = $content -replace 'BROWSER_VAR', '${{ github.event.inputs.testBrowser }}'
          $content = $content -replace 'ENV_VAR', 'test'
          $content | Set-Content src/main/resources/conf/cloudEnv.properties
        shell: powershell

      - name: Run specific runner class
        run: mvn -B -q -Dtest=SSJ_Regression_Runners -DisCloud=true test
        continue-on-error: true

      - name: Generate timestamp
        id: timestamp
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          echo "::set-output name=timestamp::$(Get-Date -Format yyyy-MM-dd_HH-mm-ss_tt)"
        shell: powershell

      - name: Determine report path
        id: reportpath
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          echo "::set-output name=path::ssj-regression-reports"
        shell: powershell

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report-${{ github.run_number }}
          path: target/ssj-regression-reports/*

      - name: Push HTML Report
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          git config --global user.email "diegojuarezbusiness@gmail.com"
          git config --global user.name "iamdez99"
          git stash
          git fetch
          git checkout gh-pages
          git stash pop
          mkdir -p ${{ steps.reportpath.outputs.path }}
          mv target/ssj-regression-reports/*.html ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html
          git add .
          git commit -m "Publishing cucumber report ${{ github.run_number }}"
          git push -f https://${{ env.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Test Results and Append to Index File
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          if (Test-Path "ssj-regression-test-results.html")
          {
              $content = Get-Content ssj-regression-test-results.html -Raw
              $content = $content -replace '<h1>.*</h1>', '<h1>SSJ Regression Test Results</h1>'
              $content += "`n<h3><a href='${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>"
              $content | Set-Content ssj-regression-test-results.html
              git add ssj-regression-test-results.html
              git commit -m "Update ssj-regression-test-results.html"
          }
          else
          {
              "<h1>SSJ Regression Test Results</h1>" | Set-Content -Encoding ASCII ssj-regression-test-results.html
              "<h3><a href='${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html'>Test Report ${{ steps.reportpath.outputs.path }}/report-${{ steps.timestamp.outputs.timestamp }}.html</a></h3>" | Out-File -Append -Encoding ASCII ssj-regression-test-results.html
              git add ssj-regression-test-results.html
              git commit -m 'Create ssj-regression-test-results.html'
          }
          git push https://${{ env.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          POWERSHELL_TELEMETRY_OPTOUT: 1