name: PLATFORM BUSINESS - SSJ SMOKE TESTS

on:
  workflow_dispatch:
    inputs:
      testBrowser:
        description: 'Browser'
        required: true
        default: 'chrome'
      runnerFile:
        description: 'Name of runner file'
        required: true
        default: 'SSJ_Smoke_Runners'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ".99"
      SCREEN_RESOLUTION: "1280x1024x24"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Replace variables in cloudEnv.properties
        run: |
          sed -i "s/SIDE_DOOR_USERNAME/${{ secrets.SIDEDOORUSERNAME }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/SIDE_DOOR_PASSWORD/${{ secrets.SIDEDOORPASSWORD }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/BROWSER_VAR/${{ github.event.inputs.testBrowser }}/g" src/main/resources/conf/cloudEnv.properties
          sed -i "s/ENV_VAR/test/g" src/main/resources/conf/cloudEnv.properties

      - name: Run specific runner class
        run: mvn -B -q -Dtest=SSJ_Smoke_Runners -DisCloud=true test
        continue-on-error: true

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-report
          path: target/ssj-smoke-reports/*

      - name: Push HTML Report
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "diegojuarezbusiness@gmail.com"
          git config --global user.name "iamdez99"
          git checkout -b gh-pages
          mv target/ssj-smoke-reports/*.html .  # Move HTML report to root
          git add .
          git commit -m "Publishing cucumber report"
          git push -f https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages